# Generated by Django 4.2.7 on 2024-06-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_comp_main', '0002_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='image',
            table='image',
        ),
    ]
