# Generated by Django 4.2.7 on 2024-07-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_comp_main', '0004_basket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'managed': False},
        ),
    ]
