# Generated by Django 4.2.7 on 2024-07-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_comp_main', '0005_alter_basket_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='basket',
            table='photo_comp_main_basket',
        ),
    ]
